# Generated by Django 4.0.6 on 2022-07-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
